### PR TITLE
Dash panel

### PR DESCRIPTION
**Pull request by vaidotasp**
Okay so I have got here a basic events page dashboard.

Events page is responsible for: 

- Fetching events
- Filtering events based on date, location or category

Right now this is mocking API calls but I am happy to start implementing real API calls. So this potentially may not be ready for merge but I wanted to get started and get some feedback.

### CODE REVIEW

**Comment by vaidotasp** [comment]
I think this basically works, but it does not have "Load More" pagination functionality and some of those filters I set up may be a bit wonky. They work but they need some more work for sure. I do not want for this PR to get any bigger than it is. @lkaratun if you can take a look and tell me what you think, I'd like to reduce the scope of the PR and get at least some functionality into the dev branch to continue working.

**Comment by lkaratun** [comment]
Hi @vaidotas, thanks for implementing this! Unfortunately I'm out of town and don't have a laptop with me so I'll only be able to have a look at it on the 27th when I get back home. Feel free to merge the pr if you need it before then, or just branch the next feature off of it.

**Comment by lkaratun** [comment]
One thing I noticed is that you have my commits in your branch, why is that? I'm wondering if it's possible to clean up the history (get rid of some commit duplicates) before merging?

**Comment by vaidotasp** [comment]
Yeah I think that I did something wrong with my rebase. Let me see if I can figure out how to clean up the history.

**Pull request closed without merging**
