### PR TITLE
Eventpage rework

### PR DESCRIPTION
**Pull request by vaidotasp**
Okay so I think this is ready to be tested. As far as I can tell functionality (leave, join, delete) works as intended. There may be styling issues and some refactoring needed to be done because right now there is a lot of conditional logic and various methods on this.

I am open to suggestions.
#75 #
@lkaratun

### CODE REVIEW

**Comment by lkaratun** [comment]
Thanks for implementing @vaidotasp, looks pretty good!
One thing I noticed: after joining an event the "Join" button changes to "Leave" but after about a second turns into "Join" again. 
Also, after creating an event with 6+ max attendees (what does 6+ even mean actually? it should probably be just 6), the details page says "5 spots left". 
Could you please have a look at these issues, and also rebase on the latest dev? Thanks in advance =)

**Comment by lkaratun** [comment]
Oh, and also the "Delete event" button doesn't show up for me, not sure if I'm doing something wrong.

**Comment by vaidotasp** [comment]
Thanks for testing! I'll rebase against the latest dev branch and dig into it.

**Comment by vaidotasp** [comment]
Is there any testing to be done on this @lkaratun ? Do not want to merge if there are still bugs.

**Comment by trolleksii** [comment]
So for me, join/leave works like charm, I could also delete events that I created. Some minor things I have noticed:
1. I had event with `min_people` set to 4 and max people set to null. This event had 3 attendees including the author. The page displayed `-3 spot(s) left`.
2. If event is fully booked, user still can see green button `Join`. It's not working but maybe we should put some accent to it, like make it grey.
3. Does not display events without date, and displays `,` if `place` is null.
4. More like a proposal, we can display who exactly joined the event, from endpoint `events/:id/attendees.

**Comment by vaidotasp** [comment]
> So for me, join/leave works like charm, I could also delete events that I created. Some minor things I have noticed:
> 
> 1. I had event with `min_people` set to 4 and max people set to null. This event had 3 attendees including the author. The page displayed `-3 spot(s) left`.
> 2. If event is fully booked, user still can see green button `Join`. It's not working but maybe we should put some accent to it, like make it grey.
> 3. Does not display events without date, and displays `,` if `place` is null.
> 4. More like a proposal, we can display who exactly joined the event, from endpoint `events/:id/attendees.

Appreciate the feedback!
I'll jump on fixing some of these issues today. Will track the progress on this comment.

- Handling the case where `max_people` is `null`
- Handling the case where `date` is not set
- Handling the case where `place` is not set
- If event is full, "Join" button should not be showing up
- Display users who joined by showing their names or avatars or some other indication.

**Comment by lkaratun** [comment]
Hey @vaidotasp, I honestly think we should merge this PR before it diverges to much from the dev branch. It will make it much easier for me to test the app overall and note the things that need to be done/changed. We can always make bug fixes in subsequent PRs. What do you say?

**Comment by vaidotasp** [comment]
> Hey @vaidotasp, I honestly think we should merge this PR before it diverges to much from the dev branch. It will make it much easier for me to test the app overall and note the things that need to be done/changed. Right now I can't really view, join or leave the event which makes testing a bit hard. And we can always make bug fixes in subsequent PRs. What do you think?

That's fine. I agree that with larger PRs I have a hard time keeping in sync with the dev branch. Especially, when there are a lot of fundamental changes on backend.
I will document bugs in the issue #69  and we can merge this one as is and fix it up after.

**Comment by trolleksii** [comment]
We had one 'fundamental` change in backend, introducing author_id and fixing bug that didn't allowed to delete events. It happened because of lack of experience and poor planning at the first stage. That doesn't sound like a lot to me. That sort of thing is inevitable when you are in active development and don't have any commitments to customer yet.

**Pull request merged**
