### PR TITLE
Events page fix filter

### LINKED ISSUE #98: EventList Page should have the same activity, location search components
Eventlist page should use the same activity and location components from create new page. The only difference should be that users cannot create new activities or locations from this view.

### PR DESCRIPTION
**Pull request by vaidotasp**
PR implements the Location and Activity search components in the `events` page. Should close #98, #50  
- Fixed bug with date formatting #105 , removed moment, added date-fns (I think formatting is simpler now)
- You can filter by location or activity

Issues noticed: 
- Clear button not working (it clears the results but not the inputs) - This will need to be fixed later.

### CODE REVIEW

**Comment by lkaratun** [comment]
To be honest, I kind of liked the old activity picker behaviour, in that on click it gave you a list of options to choose from, rather than a blank input box which a user probably doesn't know what to type in. I think it's even more important to choose existing options on the event creation page so that we don't get a lot of synonyms or different wordings of the same kind of activity.

**Comment by vaidotasp** [comment]
hmmm. So your thoughts would be to keep Activity Picker in the old style (drop down upon clicking), but have the location search being dynamic that shows results upon typing?

**Comment by lkaratun** [comment]
Ideally both of them would show a dropdown on click that would update as user starts typing

**Comment by vaidotasp** [comment]
Okay so I fixed a few issues.
* Simplified date formatting on Event component. It does not show time, just the date.
* Activity picker is dynamic, fetching all activities and then we regex match the closest as user types
* Same is done with location picker, fetches all places in db (almost 1k places is about 48kb) and matches regex

**Comment by vaidotasp** [comment]
> * pressing enter on a blank field produces an error: `TypeError: Cannot read property 'toLowerCase' of undefined`. It could be related to my hacky solution to make the search case insensitive.

Definitely a bug, I will take a look!
>* when Activity field is focused, it would be better if tab moved focus to the City field, and up/down arrows moved focus within the dropdown
I agree about tabbing, I will see how I can get arrow movement implemented, there is probably an example I can re-use somewhere on codepen.

>* I was hoping a click on the City field would open a pop-up with several of the top values shown. I'm guessing it shouldn't be too hard to add, given the fact that Activity field already behaves the same way?
Yeah this is easy to switch on. But I intentionally did not, I thought because of the number of entries, showing any of them would be redundant, but yes I can show some random 5 or so cities if that would be better UX?

Last two bullets should be easy to fix!

**Comment by lkaratun** [comment]
Look great @vaidotasp, thanks for all the work!

**Pull request merged**
