### PR TITLE
Refactor db connection 

### PR DESCRIPTION
**Pull request by trolleksii**
1. Refactored db module to use `Pool` class instead of `Client`, due to the fact that client choke on large amount of requests/sec.
2. Added more fake data to populate db:
  - 10 users
  - 10 activities
  - 993 places
  - 100 events
  - 500 event attendees
User data looks like real, places are major countries/cities, activities and events are made from random nonsense text.

### CODE REVIEW

**Comment by lkaratun** [comment]
Hey @trolleksii , thank you, all PRs are still useful (I'm planning to keep improving this project at least for a little while, although at a slower pace). 
Can you clarify if all the data you're talking about is in the prod DB already?

**Comment by trolleksii** [comment]
> Hey @trolleksii , thank you, all PRs are still useful (I'm planning to keep improving this project at least for a little while, although at a slower pace).
> Can you clarify if all the data you're talking about is in the prod DB already?

No, data is in `test_db.json` file. DB population should be performed manually with 
```
cd ./backend/src/utils
node populate_db.js test_db.json
```

**Comment by lkaratun** [comment]
To be honest, I'd prefer having sensible value for event names and especially activity types. I think it's better to have fewer good ones than a lot of ones with nonsensical text.

**Comment by lkaratun** [comment]
@trolleksii Do you want to submit a new PR with just the DB connection changes? That part was pretty good!

**Pull request closed without merging**
