### PR TITLE
Add bio field on register page

### PR DESCRIPTION
**Pull request by vaidotasp**
- Removed AuthButton component as it does not seem to be used for anything
- Removed placholders for Twitter and Facebook login on register page
- Added bio field (optional) on register page

#107

### CODE REVIEW

**Comment by lkaratun** [comment]
Hey @vaidotasp , thanks for the PR! 
Do you want to change the bio field from `input` to `text`? I think it will make it more user friendly.
Also, should we make the `Last name` field not required?  The motivation behind this is to make the registrration process as painless as possible.

**Comment by vaidotasp** [comment]
Agreed, no reason to require last name. And I can certainly do the `text` instead of `input`, I was just reusing `input` for convenience.

**Comment by vaidotasp** [comment]
Okay, ready for testing @lkaratun !

**Comment by lkaratun** [comment]
Look good, thanks @vaidotasp !

**Pull request merged**
