### PR TITLE
Fix accepted field names

### PR DESCRIPTION
**Pull request by lkaratun**
Change accepted field name to match DB column names

### CODE REVIEW

**Comment by lkaratun** [comment]
@trolleksii Have a look please

**Comment by trolleksii** [comment]
Why do we need to change names back to underscores? I thought camel case is appropriate style in JS, that's why I changed the names to camel case in the first place.

**Comment by lkaratun** [comment]
Because they aren't properly written into the DB since column names are in pothole case

**Comment by trolleksii** [comment]
DB is abstract, `pg` does conversion of all names. That's just the matter of preferences. If changed to use underscore instead of camel case, API will return names with underscore which aren't common style in JS.
I do not mind, just want to make sure if that's what you want. If so feel free to proceed with merge.

**Comment by lkaratun** [comment]
Hmm, I didn't realize `pg` was supposed to handle the conversion. I think it means there is an error in that part then, because it wasn't properly inserting first name and last name into the DB on `auth/register` call when it was passed in camel case. It's probably better to fix it then rather that changing it to pothole.

**Comment by trolleksii** [comment]
You are right, it just converts everything to lower case, so if input will be `{firstName: 'Somename'}` output will be `{firstname: 'Somename'}`. I just didn't noticed it. Just tested, works ok with camel case input, but do not work if field names differ in any way from 'firstName' and 'lastName'.
So to eliminate any ambiguity it will be better to stick to plane lowercase or underscores. But it has to be consistent across all code.

**Comment by trolleksii** [comment]
All mentioned changes were made as part of PR #36

**Pull request closed without merging**
