### PR TITLE
adding favicon

### PR DESCRIPTION
**Pull request by vaidotasp**
Adding a simple favicon.
screen shot 2019-02-09 at 6 41 36 am
screen shot 2019-02-09 at 6 41 46 am

### CODE REVIEW

**Comment by lkaratun** [comment]
Nice, that was on my list of things to do!
I was just thinking -- would it be better to capitalize both letters, since that's how they are in the logo?

**Comment by vaidotasp** [comment]
Yeah that could be better actually. I can update this and see how it looks like.

**Comment by vaidotasp** [comment]
f2

Alright, how is this one?

**Comment by lkaratun** [comment]
Looks great!

**Pull request merged**
