### PR TITLE
Image processing

### PR DESCRIPTION
**Pull request by trolleksii**
Added additional endpoint to upload event image, and modified logic to upload all images to cloudinary CDN and downscale them if its needed. 
Cloudinary credentials can be set with envvars:
`CLOUDINARY_NAME` - cloud name 
`CLOUDINARY_KEY` - API key
`CLOUDINARY_SECRET` - API secret
Few questions before I'll merge it:
1. Maybe we don't need 2 endpoints? I did that because it's explicitly states what kind of image it is. All uploads will be stored in 2 different folders in the cloud, and I can make sure that each user has only one avatar and subsequent uploads will overwrite it. Additionally, if we'll choose to add several images to the same event I can refactor do so, more or less easily.
It can be done with parameters, but it will take more time and I guess readability will suffer.
2.  Do we need some sort of parametrization in the API in terms of image transformation? Like resize to some specific size, or rotate. Or we can live with some hard-coded values, like no more than 500x500 px?

### CODE REVIEW

**Comment by lkaratun** [comment]
Thanks for implementing Alex!
Can the image endpoint be merged with the event creation/changing endpoints? (same for the users endpoints)
I think it's fine to have just default resizing for now, we can add more options later if we need them.

**Comment by trolleksii** [comment]
So at the moment they are `POST events/images` and `POST users/image`, so they are grouped with user/event related endpoints correspondingly. Is that what you mean?

**Comment by trolleksii** [comment]
Merging, as there are no objections/comments

**Comment by lkaratun** [comment]
I meant adding an image field to the `POST users` endpoint. Do you think it's possible?

**Comment by trolleksii** [comment]
I guess so, `muitipart/form-data` supports passing raw json and binary files in one request. But it seems that you'll have to create response body manually. That's what I googled just now:
https://stackoverflow.com/questions/9081079/rest-http-post-multipart-with-json

**Comment by trolleksii** [comment]
> I meant adding an image field to the `POST users` endpoint. Do you think it's possible?

So I tried to implement this on and it's not pretty. Biggest issue is with cloudinary module, which automatically parses file from body and pushes it to the cloud. So we would have a situation when request bounced back by sql would yet store images in the cloud. I believe its not worth spending more time.
@lkaratun

**Comment by trolleksii** [comment]
What we can easily adjust though is leave just one simple endpoint. Store everything in one place in the cloud. Stores one image and returns its url.

**Comment by lkaratun** [comment]
Alright, let's keep the /image endpoints then (both of them). I think it's better to store images separately. Is there a way to put them into different folders depending on type?

**Comment by trolleksii** [comment]
Now I'm passing name of the folder to store the file in to the uploader module, 'users' and 'events', so it's kind of predefined.

**Comment by lkaratun** [comment]
Ok great!

**Pull request merged**
