### PR TITLE
Starting with Create React App and Prettier

### PR DESCRIPTION
**Pull request by vaidotasp**
Starting with the boilerplate of CRA to get things going. Also adding Prettier setup so we can use the same coding style.

#2

### CODE REVIEW

**Comment by lkaratun** [comment]
Looks good to me. 
The only thing is -- should we merge this into the dev branch (if we decide to go this route)?

**Comment by vaidotasp** [comment]
Good point, I pushed this up before I thought about the dev branch route. If we decide to go that way, is it possible to "redirect" this PR towards new DEV branch? Just curious as I have not done that before.

**Comment by lkaratun** [comment]
I don't think you can unfortunately (at least I don't see the option on my side). Do you mind making a new PR for the dev branch?

**Comment by vaidotasp** [comment]
I think I was able to do it. Next to PR name there is a "Edit" button where you can change the base branch for the PR.

**Comment by lkaratun** [comment]
Nice!

**Pull request merged**
