### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by lkaratun**
I tweaked styling for the register/login page, and a little bit for the front and profile pages. Also started refactoring the styled components that are used in multiple React components into a `shared` folder.
The register page looks like on the screenshot below, let me know if you want anything changed @vaidotasp. The "Optional fields" thing is just a temporary solution until I have time to make a good looking and clear indicator of what fields are and are not mandatory (let me know what would be the best way to make it look if you have any ideas plz, because I'm personally not quite sure).
image

### CODE REVIEW

**Comment by vaidotasp** [comment]
hey @lkaratun ! I like the new look and feel, awesome.
- Create New Event page "back" and "create" buttons are not aligned, probably something got jacked with the new styles? Probably easy fix:
image

As far as optional fields question goes, not sure either. But if we look into some known websites it seems that they want to create as little friction as possible. Here is the meetup.com register page:
image
So optional fields do not even exist, it is only Name, Email and Password (or Google Auth).

Discord seems to have similar idea:
image

Maybe we need to consider doing similar approach and then have a little notification or some other UI indicator to user to finish theirs profile setup?

**Comment by lkaratun** [comment]
Ok so I finally got back to this. I refactored most of the buttons to reuse styled defied in the `shared/Buttons.js` file and fixed the discrepancies. @vaidotasp feel free to click through the app to check whether I missed or broke something along the way, otherwise I can just merge this.
I completely agree with your suggestions regarding account creation, I think we should document it in an issue and implement it in a separate PR. Does this sound reasonable?

**Comment by vaidotasp** [comment]
Hey @lkaratun ! I will review the PR today/tomorrow and try and click around the site to make sure nothing is broken. I agree about the separate issue/PR for account creation. Best keep PRs semi-contained :)

**Comment by vaidotasp** [comment]
For some reason date input got a bit janky:
image
Here is the fix:
```javascript
//DateSelector.js component
padding:10px;
margin: 7px 0px 5px
```

Similar issue with clear button
```
//events.js => ClearButton component
height: 40px;
margin: 7px 0 5px;
```
That should do it.

**Pull request merged**
